name: CI Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run full Maven build
        run: |
          mvn clean verify
          mvn org.apache.maven.plugins:maven-checkstyle-plugin:check
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs
          mvn org.owasp:dependency-check-maven:check
