name: CI Pipeline

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # 3. Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Cache OWASP Dependency-Check DB
      - name: Cache Dependency-Check DB
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check-db-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      # 5. Run full Maven build + plugins
      - name: Run Maven Verify (Build + Test + Lint + SAST + SCA)
        run: mvn clean verify
